import bycrypt from "bcryptjs";
const data = {
  users: [
    {
      name: "Aniket ",
      email: "Admin@admin.com",
      password: bycrypt.hashSync("1234", 9),
      isAdmin: true,
    },
    {
      name: "Riya",
      email: "blabla@exe.com",
      password: bycrypt.hashSync("1234", 9),
      isAdmin: true,
    },
    {
      name: "Ujju",
      email: "cuju1213@cat.com",
      password: bycrypt.hashSync("5678", 9),
      isAdmin: true,
    },
    {
      name: "Ramesh",
      email: "fskjdfgb@cat.com",
      password: bycrypt.hashSync("5678", 9),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "Wheezel",
      category: "liver Care",
      image: "/images/m1.jpg",
      price: 120,
      countInStock: 10,
      brand: "JnJ",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Gaumutra",
      category: "liver Care",
      image: "/images/m2.jpg",
      price: 120,
      countInStock: 20,
      brand: "JnJ",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Crocine",
      category: "headache",
      image: "/images/m4.jpg",
      price: 120,
      countInStock: 0,
      brand: "JnJ",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Tuks",
      category: "fever",
      image: "/images/m5.jpg",
      price: 120,
      countInStock: 10,
      brand: "JnJ",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Crocineh",
      category: "headache",
      image: "/images/m6.jpg",
      price: 120,
      countInStock: 11,
      brand: "JnJ",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Crocineg",
      category: "stomach",
      image: "/images/m6.jpg",
      price: 120,
      countInStock: 10,
      brand: "JnJ",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Zandu",
      category: "stomach",
      image: "/images/m3.jpg",
      price: 220,
      countInStock: 5,
      brand: "JnJ",
      rating: 3.5,
      numReviews: 10,
      description: "high quality product",
    },
  ],
};
export default data;
