const data = {
  products: [
    {
      _id: "1",
      name: "Wheezel",
      category: "liver Care",
      image: "/images/m1.jpg",
      price: 120,
      countInStock: 10,
      brand: "JnJ",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "2",
      name: "Gaumutra",
      category: "liver Care",
      image: "/images/m2.jpg",
      price: 120,
      countInStock: 20,
      brand: "JnJ",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "3",
      name: "Crocine",
      category: "headache",
      image: "/images/m4.jpg",
      price: 120,
      countInStock: 0,
      brand: "JnJ",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "4",
      name: "Tuks",
      category: "fever",
      image: "/images/m5.jpg",
      price: 120,
      countInStock: 10,
      brand: "JnJ",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "5",
      name: "Crocine",
      category: "headache",
      image: "/images/m6.jpg",
      price: 120,
      countInStock: 11,
      brand: "JnJ",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "6",
      name: "Crocine",
      category: "headache",
      image: "/images/m6.jpg",
      price: 120,
      countInStock: 10,
      brand: "JnJ",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "7",
      name: "Zandu",
      category: "stomach",
      image: "/images/m3.jpg",
      price: 220,
      countInStock: 5,
      brand: "JnJ",
      rating: 3.5,
      numReviews: 10,
      description: "high quality product",
    },
  ],
};
export default data;
